version: "v2.29.7"
services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: azizhendili/timesheet-devops:1.0.0
    restart: on-failure
    ports:
      - 8882:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://192.168.50.4:3306/mydatabase?createDatabaseIfNotExist=true" ,
        "spring.datasource.username" : "springuser",
        "spring.datasource.password" : "springpassword",
        "spring. jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db :